#!/usr/bin/env bash
# this script to install nginx
sudo apt-get update -y
sudo apt-get -y install nginx
sudo ufw allow nginx 'Nginx HTTP'
echo "Hello World!" > sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
