#!/usr/bin/env bash
# this script to install nginx
sudo apt-get update -y
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo sed -i "s/listen 80;/listen 80;/" /etc/nginx/sites-available/default
sudo ufw allow nginx 'Nginx HTTP'
sudo service nginx start
