#!/usr/bin/env bash
# this script to do redection
sudo apt-get update -y
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
my_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/areejslama permanent;"
sudo sed -i "s/server_name _;/$my_string/"  /etc/nginx/sites-enabled/default
sudo service nginx restart
