#!/usr/bin/env bash
# this script do custome 404 not found page
sudo apt-get update -y
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
my_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/areejslama permanent;"
sudo sed -i "s/server_name _;/$my_string/"  /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
my_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$my_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
