#!/usr/bin/env bash
# this script to install proxy
sudo apt-get -y update
sudo apt-get -y install haproxy
server_config=\
"
frontend areej_frontend
        bind *:80
        mode http
        default_backend areej_backend

backend areej_backend
        balance roundrobin
        server 500025-web-01 3.89.155.41:80 check
        server 500025-web-02 54.208.154.58:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
