#!/bin/bash/env
# this script to create mysql backup
day=$(date +%d)
month=$(date +%m)
year=$(date +%y)
file_name="$day-$month-$year.tar.gz"
mysqldump -u root --password='$1' --all-databases > backup.sql
tar -czvf "$file_name" backup.sql
