#!/usr/bin/env bash
# this script tells a story
while IFS=":" read -r username password uid gid user_info home_directory shell
do
    echo "The user $username is part of the $gid gang, lives in $home_directory, and rides $shell."
    echo "User $uid's place is protected by the passcode $password."
    echo "More info about the user $username: $user_info"
done < /etc/passwd
