#!/usr/bin/env bash
# this script display best school string 10 times with bad luck for the 4th loop iteration and good luck for the 8th loop iteration
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
then
	echo "bad luck"
elif [ $i -eq 8 ]
then
	echo "good luck"
else
	echo "Best School"
fi
i=$((i+1))
done
