#!/usr/bin/env bash
# this script display clock
Hour=0
while [ $Hour -le 12 ]
do
	echo "Hour: $Hour"
	Hour=$((Hour+1))
minutes=1	
while [ $minutes -le 59 ]
do
echo "$minutes"
minutes=$((minutes+1))
done
done
