#!/usr/bin/env bash
# this script to config nginx
server {
        listen 80 default_server;
        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

	server_name _;
add_header X-Served-By 500025-web-01;
 location /hbnb_static {
     alias /data/web_static/current/;
    }
        rewrite ^/redirect_me https://github.com/areejslama permanent;
location / {

                try_files $uri $uri/ =404;
 location /airbnb-onepage {
        proxy_pass http://0.0.0.0:5000/airbnb-onepage;
}
 location ~ ^/airbnb-dynamic/number_odd_or_even/<int:n> {
        proxy_pass http://0.0.0.0:5001/number_odd_or_even/\$1;
}
 location /api/ {
        proxy_pass http://0.0.0.0:5002/api;
}
