#!/usr/bin/env bash
# this script to config nginx
server {
        listen 80 default_server;

    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By 500025-web-01;
    location /hbnb_static { 
        alias /data/web_static/current/;
    }
location / {
                try_files $uri $uri/ =404;
}
 location /api/ {
        proxy_pass http://0.0.0.0:5002;
}
